[2025-02-17T14:51:15.011+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.load_to_s3 manual__2025-02-17T14:51:02.776152+00:00 [queued]>
[2025-02-17T14:51:15.022+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.load_to_s3 manual__2025-02-17T14:51:02.776152+00:00 [queued]>
[2025-02-17T14:51:15.023+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-17T14:51:15.042+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_to_s3> on 2025-02-17 14:51:02.776152+00:00
[2025-02-17T14:51:15.047+0000] {standard_task_runner.py:57} INFO - Started process 298 to run task
[2025-02-17T14:51:15.051+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'load_to_s3', 'manual__2025-02-17T14:51:02.776152+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpwuf55lfu']
[2025-02-17T14:51:15.055+0000] {standard_task_runner.py:85} INFO - Job 22: Subtask load_to_s3
[2025-02-17T14:51:15.115+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_Pipeline.load_to_s3 manual__2025-02-17T14:51:02.776152+00:00 [running]> on host 471abd7d1b7d
[2025-02-17T14:51:15.206+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T14:51:02.776152+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-17T14:51:02.776152+00:00'
[2025-02-17T14:51:15.212+0000] {credentials.py:1124} INFO - Found credentials in environment variables.
[2025-02-17T14:51:18.863+0000] {load_s3.py:42} INFO - File successfully uploaded from 'Processed_Data/final_combined_data.csv' to s3 bucket 'etlbucket-bd'
[2025-02-17T14:51:18.865+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-17T14:51:18.875+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Pipeline, task_id=load_to_s3, execution_date=20250217T145102, start_date=20250217T145115, end_date=20250217T145118
[2025-02-17T14:51:18.960+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-17T14:51:18.978+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
