[2025-02-17T14:54:06.191+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_postgres manual__2025-02-17T14:54:03.136308+00:00 [queued]>
[2025-02-17T14:54:06.216+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_Pipeline.extract_postgres manual__2025-02-17T14:54:03.136308+00:00 [queued]>
[2025-02-17T14:54:06.217+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-17T14:54:06.238+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_postgres> on 2025-02-17 14:54:03.136308+00:00
[2025-02-17T14:54:06.245+0000] {standard_task_runner.py:57} INFO - Started process 342 to run task
[2025-02-17T14:54:06.251+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ETL_Pipeline', 'extract_postgres', 'manual__2025-02-17T14:54:03.136308+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline.py', '--cfg-path', '/tmp/tmpvy_56m98']
[2025-02-17T14:54:06.257+0000] {standard_task_runner.py:85} INFO - Job 24: Subtask extract_postgres
[2025-02-17T14:54:06.342+0000] {task_command.py:416} INFO - Running <TaskInstance: ETL_Pipeline.extract_postgres manual__2025-02-17T14:54:03.136308+00:00 [running]> on host 471abd7d1b7d
[2025-02-17T14:54:06.486+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_Pipeline' AIRFLOW_CTX_TASK_ID='extract_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T14:54:03.136308+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-17T14:54:03.136308+00:00'
[2025-02-17T14:54:06.490+0000] {extract_postgresql.py:23} INFO - Creating connection to RDS Postgresql Database
[2025-02-17T14:54:07.602+0000] {extract_postgresql.py:32} INFO - Connection established
[2025-02-17T14:54:07.605+0000] {extract_postgresql.py:47} INFO - Loading postgres data
[2025-02-17T14:54:07.640+0000] {logging_mixin.py:154} WARNING - /opt/***/src/etl/extract_postgresql.py:48 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-02-17T14:54:12.076+0000] {extract_postgresql.py:49} INFO - Loaded 10639 records from the database
[2025-02-17T14:54:12.078+0000] {extract_postgresql.py:52} INFO - PostgreSQL connection closed.
[2025-02-17T14:54:12.092+0000] {extract_postgresql.py:70} INFO - Postgres Data Validated Successfully
[2025-02-17T14:54:12.218+0000] {extract_postgresql.py:73} INFO - Postgres data extracted and saved to path 'Processed_Data/valid_postgres_data.csv'
[2025-02-17T14:54:12.220+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-17T14:54:12.235+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ETL_Pipeline, task_id=extract_postgres, execution_date=20250217T145403, start_date=20250217T145406, end_date=20250217T145412
[2025-02-17T14:54:12.349+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-17T14:54:12.381+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
